spring:
  data:
    mongodb:
      uri: mongodb://mongodb:27017/security
  redis:
    host: redis
    port: 6379

security:
  ignored: /users/**/profiles

management:
  security.enabled: false

br.com.security.jwt:
  alias: jwtKey
  store-pass: simpleStorePass
  key-store: classpath:keystore.jks
  key-pass: simpleKeyPass
